version: 2.1
jobs:
  build_and_test:
    macos:
      xcode: "11.3.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Prepare for Swift Package Manager
          command: |
            for ip in $(dig @8.8.8.8 bitbucket.org +short); do ssh-keyscan bitbucket.org,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
            xcodebuild -resolvePackageDependencies
      - run:
          name: Fastlane
          command: bundle exec fastlane test
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2.1
  test:
    jobs:
      - build_and_test